{application,villain_selection,
             [{modules,['Elixir.VillainSelection',
                        'Elixir.VillainSelection.Helpers',
                        'Elixir.VillainSelection.Validation']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,jason]},
              {description,"villain_selection"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
